---
- block:
  - name: Add Certbot ppa
    apt_repository:
      repo: ppa:certbot/certbot
      state: present
      filename: certbot

  - name: Install certbot packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
    - certbot
    - python3-certbot-nginx
    - python3-certbot-dns-route53

  - name: Generate let's encrypt certificate
    shell: |
      certbot certonly --dns-route53 -d {{ jenkins.domain }} --non-interactive --agree-tos -m '{{certbot.email}}'
    register: proc

  - debug: var=proc.stdout_lines
